### ISSUE TITLE
Alpine 3.8 EOL

### ISSUE THREAD

**Issue by tianon** [docker-library/haproxy#114]
https://github.com/docker-library/official-images/pull/8089 has officially removed `alpine:3.8` as the underlying Alpine 3.8 series is now end of life.

Our HAProxy 1.6 Alpine image is still `FROM alpine:3.8`.  The reasons for this are entangled somewhat in https://github.com/docker-library/haproxy/issues/74 and https://github.com/docker-library/haproxy/issues/96, but the TL;DR is that OpenSSL 1.1+ would (maybe?) be a breaking change for users, so we opted to only perform that update in HAProxy 1.7+.

The catch is that we now have to revisit that decision and either update HAProxy 1.6 to at least Alpine 3.9 (but might as well be 3.11 or even the new 3.12 at that point) or remove it entirely.  It is *not* EOL until ~2020-Q4 (still under "critical fixes only" maintenance currently) per https://www.haproxy.org/.

**Comment by tianon** [comment]
@TimWolla hoping you might have some sage advice here :pray: :sweat_smile: :heart:

How bad would it be to update HAProxy 1.8 to Alpine 3.11 or 3.12 and thus OpenSSL 1.1+?

**Comment by TimWolla** [comment]
> How bad would it be to update HAProxy 1.8 to Alpine 3.11 or 3.12 and thus OpenSSL 1.1+?

I have no idea, I run the current HAProxy version.

However I expect users that *still* run HAProxy 1.6 to be super interested in stability, so I'd rather remove HAProxy 1.6 early instead of changing something about it in the last 6 months of the lifetime. An upgrade to the 1.8 LTS should be a no-brainer in most cases (configuration is ~100% compatible). If you are not doing that you don't want to change anything at all.
