### ISSUE TITLE
Hard DNS resolving 

### ISSUE THREAD

**Issue by OkenKhuman** [docker-library/haproxy#124]
Hi I am trying to proxy two mqtt broker on same swarm through through single port by using SNI. My HAProxy config is 
```
resolvers docker
  nameserver dns "127.0.0.11:53"
defaults
  timeout client 30s
  timeout server 30s
  timeout connect 5s
listen mqtt
  bind *:1883
  use-server mqtt_app_1 if { req_ssl_sni -i mqtt1.ns1.logicbee.dev }
  server     mqtt_app_1 mqtt_1:1883 check resolvers docker resolve-prefer ipv4
  use-server mqtt_app_2 if { req_ssl_sni -i mqtt2.ns1.logicbee.dev }
  server     mqtt_app_2 mqtt_2:1883 check resolvers docker resolve-prefer ipv4
```
i got the below error
```
mult_serv_proxy2.1.sm4o91a6ocw7@node0    | [NOTICE] 195/185652 (1) : haproxy version is 2.2.0
mult_serv_proxy2.1.sm4o91a6ocw7@node0    | [NOTICE] 195/185652 (1) : path to executable is /usr/local/sbin/haproxy
mult_serv_proxy2.1.sm4o91a6ocw7@node0    | [ALERT] 195/185652 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:12] : 'server mqtt_app_1' : could not resolve address 'mqtt_1'.
mult_serv_proxy2.1.sm4o91a6ocw7@node0    | [ALERT] 195/185652 (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:14] : 'server mqtt_app_2' : could not resolve address 'mqtt_2'.
mult_serv_proxy2.1.sm4o91a6ocw7@node0    | [ALERT] 195/185652 (1) : Failed to initialize server(s) addr.
mult_serv_proxy2.1.42p4r0h5exw6@node0    | [NOTICE] 195/185659 (1) : New worker #1 (7) forked
```
my swarm setup works well for httpd proxied by nginx.

What could be the problem?

**Comment by wglambert** [comment]
`could not resolve address 'mqtt_1'` Can you ping that address?

**Comment by OkenKhuman** [comment]
@wglambert  I was able to ping to mqtt_1 from inside the haproxy container 
![Screenshot (243)](https://user-images.githubusercontent.com/34859716/87499790-b26bb600-c678-11ea-9743-3167e6f4cb11.png)

**Comment by wglambert** [comment]
Are you using a `docker-compose` file to start the containers? Maybe `mqtt_1` wasn't fully started when haproxy tried connecting
https://discourse.haproxy.org/t/haproxy-fails-to-start-if-backend-server-names-dont-resolve/322/11

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
