### ISSUE TITLE
Default entrypoint disables multi-process mode

### ISSUE THREAD

**Issue by arpyzo** [docker-library/haproxy#131]
Hi,

According to the HAProxy doc running with `-db` not only runs HAProxy in the foreground, but also disables multi-process mode.

_-db : disable background mode and multi-process mode. The process remains in
    foreground. It is mainly used during development or during small tests, as
    Ctrl-C is enough to stop the process. Never use it in an init script._

Wouldn't `-d` be a more appropriate choice? If not, could someone please explain the reasoning behind using `-db` so I can understand.

Thanks in advance.

**Comment by yosifkit** [comment]
We likely got `-db` from the config documentation (https://www.haproxy.org/download/2.1/doc/configuration.txt) in order to prevent a `daemon` in the users config file from causing the container to exit immediately.

```console
daemon
  Makes the process fork into background. This is the recommended mode of
  operation. It is equivalent to the command line "-D" argument. It can be
  disabled by the command line "-db" argument. This option is ignored in
  systemd mode.
```

I am concerned about the "disable ... multi-process mode", but when combined with `-W`, it still spawns workers. `-d` would not be correct, since it prints a bunch of debug output, whereas `-db` does not.

https://www.haproxy.org/download/2.1/doc/management.txt: 

```console
  -W : master-worker mode. It is equivalent to the "master-worker" keyword in
    the "global" section of the configuration. This mode will launch a "master"
    which will monitor the "workers". Using this mode, you can reload HAProxy
    directly by sending a SIGUSR2 signal to the master.  The master-worker mode
    is compatible either with the foreground or daemon mode.  It is
    recommended to use this mode with multiprocess and systemd.
```

**Comment by arpyzo** [comment]
I've verified that the parameters do indeed override each other in this way. Probably should've stared with that. I appreciate you humoring my concern.
