### ISSUE TITLE
Container always shutdown 

### ISSUE THREAD

**Issue by Issen007** [docker-library/haproxy#135]
Hi,
I'm playing around with HAProxy in a Openshift Kubernetes Container, but it seems like I have done a haproxy.cfg configuration mistake but because the container are always restarting and the logging is lacking, I can't find out the problem. 

Is there a good way to get a better logging to stdout in haproxy 2.3.1-alpine?

Thanks
Christian

**Comment by tianon** [comment]
I'm guessing your `global` block includes the `daemon` option, which tells `haproxy` to self-daemonize (which will immediately kill the container, since the main process being monitored by the container runtime has exited).

What I would suggest is trying to run it in a simpler environment such as just `docker run` so that you can more easily see exactly what's happening and capture the appropriate output.

(Although keep in mind that unfortunately, upstream haproxy logging options are a bit limited, and you'll likely need a working syslog server to really see what's happening; https://github.com/docker-library/haproxy/issues/106#issuecomment-566666069, #39)

**Comment by TimWolla** [comment]
> I'm guessing your `global` block includes the `daemon` option, which tells `haproxy` to self-daemonize (which will immediately kill the container, since the main process being monitored by the container runtime has exited).

The `-db` _should_ prevent that: https://github.com/docker-library/haproxy/blob/ced45443a115fbcc9f170c5f71c19a2b227aeb1d/2.3/docker-entrypoint.sh#L13

> (Although keep in mind that unfortunately, upstream haproxy logging options are a bit limited, and you'll likely need a working syslog server to really see what's happening; [#106 (comment)](https://github.com/docker-library/haproxy/issues/106#issuecomment-566666069)

HAProxy 1.9+ supports logging to stdout perfectly fine (as indicated by the comment you linked :smiley:). I use it myself to get my logs into journald (but not running HAProxy in Docker).

-------------

I agree with tianon's general advice, though. A simple container probably is easier with regard to debugging.

**Comment by Issen007** [comment]
Thx, I'll will test that tomorrow. 
That was correct I had the `daemon` in the `global` variable. But with a quick test to just comment out that line I still got the same issue. 

But I did have the chance to setup a HAProxy manually on a Linux host the other day and found out some other issues with the config file that I need to test. 
And I'll will test it only in Docker this time.

**Comment by Issen007** [comment]
Found the issue now for everything. 
I have a few of HAProxy 1.x SSL checks that couldn't get answer of the device in the backend. 
And when that happening is the Container automatically been shutdown and recreated. 
But when I remove does SSL checks then it works fine.
