### ISSUE TITLE
Feedback: Rewriting existing patch version tags with breaking changes causes downstream issues

### ISSUE THREAD

**Issue by jakewins** [docker-library/haproxy#137]
Realizing the versioning of the image is following haproxy itself, so making changes to the image itself while maintaining the same haproxy version gets clunky.

However, I still thought I should at least feed back: Overwriting the patch tags with [this changeset](https://github.com/docker-library/haproxy/commit/82ff028a25c55c36e8c39b16390e4e04efa2bc4a) broke downstream images that had already "done the right thing" and added the missing haproxy user. 

Maybe there's a way to provide stable tags for users that don't want breaking changes swapped in automatically. For instance, an optional additional tag level that includes an "image version" or "build id" or something: `2.3.2-alpine.1` or some such; then the breaking changes could go in as `2.3.2-alpine` *and* `2.3.2-alpine.2`, leaving users that point to `2.3.2-alpine.1` with working systems.

Please feel free to close this immediately, I just wanted to circle this back after spending the afternoon trying to figure out why CI suddenly broke :p

**Comment by tianon** [comment]
Yep, see https://github.com/docker-library/haproxy/pull/134#issuecomment-749198758 :sweat_smile:

What I'd generally suggest in this case is that you gate consumption of newer releases on a CI process, and ingest "known-good" / working versions into a separate namespace or registry (which it sounds like you might already be doing :smile:).

This is a common pattern across all the images in the Docker official images program, not really something unique to this image -- there are also rebuilds that will occur outside the control of this repo/tagging, so we can't really have a "patch" version that's actually meaningful since base OS upgrades will rebuild regardless (and may even contain "breaking" changes outside our control, like removing CAs or other security-type fixes :disappointed:):

- https://github.com/docker-library/official-images#library-definition-files
- https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what
