### ISSUE TITLE
issues with troubleshooting

### ISSUE THREAD

**Issue by ghost** [docker-library/haproxy#177]
Any chance on adding net-tools and iputils-ping to the image for basic troubleshooting as a default? I have no issue doing if I have to just would be a feature to have upfront without having to go through the hoops. Thanks

**Comment by williammeye3** [comment]
Thought about the question and I feel to define the why the need for each.

net-tools - running haproxy with a multi network; Kubernetes, Docker-Swarm, or even single node docker host that uses frontend/backend configurations (I used frontend/backend as an example although my instance is more like internal/dmz & a backend which haproxy only does tcp proxy). This ensures haproxy has connected to said networks and picked up an ip for basic routing.

iputils-ping - when troubleshooting configuration issues a ping command is the basic tool that is necessary to confirm the simplest connection status (IE= both systems can communicate on the most basic terms)

Im ok with doing the installs manually after updating but like I said it would be a nice feature to have the basics upfront. And I will be ok if the answer is no its not included to keep the image for general deployment as small as possible so there will need to be a manual install each time of these two utilities.

**Comment by williammeye3** [comment]
wglambert - Much appreciated. I will review. But I found that due to some complexity its better to do the ssl at the docker host level. 

I will be updating my readme soon but the 1000ft overview is (keeping it simple assumption being a stand alone docker dost)

1- haproxy docker container running w/ACL for certbot request reply pointing to the docker network gateway as a backend on a port such as 8888 which is on the docker host. reference link- https://serversforhackers.com/c/letsencrypt-with-haproxy
2- running stand alone commands to accomplish initial request and cert publish. reference link - https://serversforhackers.com/c/letsencrypt-with-haproxy
3- using docker volumes map the ssl truncate via a script in the /etc/letsencrypt/deploy directory - reference link see topic haproxy ssl cert auto renew - https://markontech.com/linux/install-lets-encrypt-ssl-on-haproxy/
4- setup a reverse proxy using mapped ssl from #3 to the haproxy.cfg - setup this config using the outline in this repos haproxy.cfg

Its more specific then that but like I said 1000ft overview.
