### ISSUE TITLE
Support transparent proxying

### ISSUE THREAD

**Issue by jbaramidze** [docker-library/haproxy#20]
Hello.
I'm using haproxy in docker containers to balance load of mysql cluster, and I get all connections from haproxy's addresses (and 172.17.0.1 if both haproxy and mysql containers run at same machine). 

Is there anyway I get real ip's there? I read
http://blog.haproxy.com/2013/09/16/howto-transparent-proxying-and-binding-with-haproxy-and-aloha-load-balancer/
but it requires rebuilding kernel. I was hoping this container would have appropriate kernel configuration, but it doesn't.

**Comment by tombull** [comment]
Transparent proxying is possible in a docker container, but there are various security implications. I've built a docker container for HAProxy that supports transparent proxying that you might want to check out: [docker hub](https://hub.docker.com/r/tombull/haproxy/) and [github](https://github.com/tombull/haproxy)
Note: it also does zero-downtime reloads... :smile:

**Comment by yosifkit** [comment]
The haproxy image does support the "graceful restarts" (since #17), which is now documented in https://github.com/docker-library/docs/pull/534.  But as far as the transparent proxying, it seems that requires `--net=host` and additional security privileges so I think we would be unlikely to add it to this image.  @tombull's image seems like a great place to start though (:+1: that it is `FROM haproxy`).

**Comment by tombull** [comment]
Yeah, forgot to mention that it's based on this wonderful `haproxy` container :smile:
The 'graceful' reloads thing that haproxy does *can* drop a few packets in the time between when one process drops the socket and the next takes it up. It's probably not worth worrying about unless the service has no error-recovery mechanisms or it's a mega-busy service. Because my container that does transparent proxying requires access to iptables (`NET_ADMIN` capability) it can do a slightly more advanced reload based on the technique (described here)[http://www.mail-archive.com/haproxy@formilux.org/msg06885.html] that guarantees not to drop any packets. Probably.

**Comment by tianon** [comment]
Closing since this appears to be resolved. :+1:
