### ISSUE TITLE
Use /var/run/docker.sock as backend server

### ISSUE THREAD

**Issue by Tardo** [docker-library/haproxy#202]
In 2.2 version, because the Dockerfile uses "root" user, you can mount "/var/run/docker.sock" and read it... but in older versions the user used is "haproxy"...

How i can still read to /var/run/docker.sock ? I need change the user to root in my Dockerfile?

Thanks.

**Comment by tianon** [comment]
I don't recommend running `haproxy` as `root` (nor exposing your Docker socket externally without some strict authentication, in case that's what you're doing here, since access to it _is_ root-equivilant :grimacing:), but you should be able to do so with `--user` on `docker run` or `user:` in `docker-compose.yml`.

Another option would be to create a `docker` group inside the container/image with a GID that matches the GID of the `docker` group on your host and then adding the `haproxy` user to it (or running explicitly with `--user haproxy:GID`, as in, `--user haproxy:998` with my example below):

```console
$ stat --format '%g' /var/run/docker.sock
998
```

**Comment by tianon** [comment]
(In the future, these sorts of questions/requests would be more appropriately posted to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).)
