### ISSUE TITLE
Haproxy stats not available

### ISSUE THREAD

**Issue by Stephan3555** [docker-library/haproxy#43]
Good afternoon,

i am having trouble activating stats for HaProxy. I tried it with version 1.7.8 and 1.6.3.
I always run in the errormessage in my Browser:

> Forbidden
You don't have permission to access /stats on this server.

I use the following configuration:

> ```
> global
> 
>  stats timeout 30s
> 
> defaults
>  log global
>  timeout connect 5000ms
>  timeout client 50000ms
>  timeout server 50000ms
> 
> listen stats
>  bind *:51510
>  mode http
> 
>  stats enable
>  stats hide-version
>  stats refresh 30s
>  stats show-node
>  stats auth admin:admin
>  stats uri /stats
> 
> frontend ft_myapp
>  bind *:443
>  mode tcp
>  default_backend bk_myapp
> 
> backend bk_myapp
>  balance source
>  mode tcp
>  server rgw1 192.168.210.101:443 check
>  server rgw2 192.168.210.102:443 check
>  server rgw3 192.168.210.103:443 check
> ```

If i install HaProxy in version 1.6.3 without docker the configuration works fine and I can access the stats GUI.

Is this a bug or am I missing something?

**Comment by tianon** [comment]
Are you hitting port 443, or port 51510?

I was debugging this with @wglambert, and we copied your exact configuration into a Docker image (as-is without any changes), then ran the result with `-p 51510:51510` on our `docker run` line, and then were able to hit `http://127.0.0.1:51510/stats` in a browser, log in with `admin`/`admin`, and see stats from the HAproxy instance. :confused:

(Since we can't reproduce, and there thus doesn't seem to be an issue with the image, I'm going to close. :heart:)
