### ISSUE TITLE
Alpine image using systemd wrapper

### ISSUE THREAD

**Issue by jodawill** [docker-library/haproxy#46]
Is there a reason the alpine image uses haproxy-systemd-wrapper, or was that just a copy & paste oversight? It looks like Alpine uses OpenRC. The systemd wrapper works for the most part, but it seems to be breaking the logging functionality when I use syslogd to pipe the logs to stdout.

https://github.com/docker-library/haproxy/blob/master/1.7/alpine/docker-entrypoint.sh#L12

This Dockerfile does work:

`FROM haproxy:1.7.8-alpine`
`RUN sed -i '2a/sbin/syslogd -O /dev/stdout' docker-entrypoint.sh`
`RUN sed -i 's/haproxy-systemd-wrapper/haproxy/g' docker-entrypoint.sh`

**Comment by tianon** [comment]
It's got systemd in the name because that's the primary use case it was
developed for, but it's simply a wrapper that manages a haproxy instance
such that zero-downtime configuration reloads can be performed, for example.

There's another open issue or PR discussing the syslog issue (don't have
the number handy ATM).

**Comment by tianon** [comment]
From https://manpages.debian.org/stretch/haproxy/haproxy.1.en.html:

> **`-Ds`**
> > Start in systemd daemon mode, keeping a process in foreground.

Keeping a process in the foreground is exactly what we need -- they added it for systemd, because that's how one normally runs processes in systemd, but it's useful for Docker as well (because Docker requires that processes run in the same "foregrounded daemon" way).  Even if we weren't using the `haproxy-systemd-wrapper`, we'd still be using `-Ds`.

Also, it's our entrypoint script which adds this, and only does so conditionally based on the intended command being simply `haproxy`, so it should be trivial to bypass at runtime.  If you wanted something hacky, you could go as simple as something like the following: (as discussed over in https://github.com/docker-library/haproxy/pull/39)
```console
$ docker run -dit haproxy bash -c 'syslogd -O /proc/1/fd/1 -S -D; exec haproxy -f /usr/local/etc/haproxy/haproxy.cfg -Ds'
```

**Comment by jodawill** [comment]
@tianon, thanks for the help. I've done some poking around and I see that haproxy seems to ignore signals unless you're using that wrapper. The thing I don't understand is why logging doesn't work when I start haproxy via the wrapper. I've tried adding `syslogd -O /proc/1/fd/1` to the entrypoint script and it doesn't give me any logs. Is this a known bug, or is my configuration wrong somehow?

**Comment by tianon** [comment]
Sorry for the delay -- that's a quirk of HAProxy: it will _only_ log to syslog.  I'm not sure why your starting `syslogd` didn't work, but there's more discussion of that over in https://github.com/docker-library/haproxy/pull/39.

Closing since the original question here seems to be resolved. :+1:
