### ISSUE TITLE
Reloading config on HAProxy 1.8

### ISSUE THREAD

**Issue by lpfeup** [docker-library/haproxy#54]
Is the documentation up-to-date regarding reloading the configuration on haproxy 1.8?
I am asking since the documentation still references _haproxy-systemd-wrapper_, which is not used anymore and because the entrypoint.sh now reads

> _allows for reload via "SIGUSR2"_

**Comment by yosifkit** [comment]
`haproxy-systemd-wrapper` functionality was integrated directly into haproxy with the `-W` option, so it should behave identically (ie `SIGUSR2` will work just fine to tell it to reload config).

We have yet to wordsmith the "Reloading config" section of the docs to mention that `1.8` no longer uses the wrapper script. It is on the todo list, but not critical since it works the same way.

**Comment by lpfeup** [comment]
Thank you for the clarification!

**Comment by flavioaiello** [comment]
Which reload type is recommended with 1.8? I made it this way after consulting the 1.8 instructions: https://github.com/flavioaiello/swarm-router
But I'm still not sure if the master-worker mode is the preferred way to do it...

**Comment by tianon** [comment]
It's the same for both versions: `SIGUSR2`

Thanks for the prod -- I'm going to close this issue now since the original request is solved. :+1:

For further help, I'd recommend trying [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by flavioaiello** [comment]
SIGUSR2 works according to https://cbonte.github.io/haproxy-dconv/1.8/management.html only with the master-worker wrapper. The same can be accomplished by transferring sockets between processes (as done in the image above: -x, -p and -sf switches)
