### ISSUE TITLE
100% cpu using resolvers with haproxy v1.8.9

### ISSUE THREAD

**Issue by flavioaiello** [docker-library/haproxy#68]
There is a patch fixing this issue:
- https://www.mail-archive.com/haproxy@formilux.org/msg30173.html

This is probably important for those using the latest release and dns resolvers.

**Comment by yosifkit** [comment]
I don't think we want to apply the patch manually; I'd rather wait for the next release that will have the fix. 

I'll leave the issue open so that users running into the issue can see that it is an upstream bug that should be fixed in the next version and they can pin to a previous release as a workaround (like `haproxy:1.8.8`).

**Comment by TimWolla** [comment]
This issue should be fixed as of haproxy 1.8.10 (2018-06-22): http://git.haproxy.org/?p=haproxy-1.8.git;a=commit;h=09dbc884b10a9b30dc500f45f32d1610d463a056

**Comment by tianon** [comment]
Nice! :+1:
