### ISSUE TITLE
Prometheus-exporter support

### ISSUE THREAD

**Issue by DENDarkness** [docker-library/haproxy#94]
Add the "contrib/prometheus-exporter/service-prometheus.o" module to the dockerfile for the default build
https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/#comment-144482

**Comment by tianon** [comment]
The fact that it lives under `contrib/...` is a little off-putting from an "upstream supports and recommends using this" perspective -- is there something more official than that blog post which recommends we enable this for official builds / production installations?  Perhaps some bit of official documentation for HAproxy itself?

**Comment by DENDarkness** [comment]
I saw this in a blog and I think it will simplify the monitoring of the product in kubernetes

**Comment by yosifkit** [comment]
I think it makes sense to compile it in (since it doesn't look like it can be added later).

- it was a blog post on haproxy.com by a Senior Systems Engineer
- [debian](https://salsa.debian.org/haproxy-team/haproxy/blob/experimental-2.0/debian/rules#L21) has enabled it
- gentoo has a [build flag](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-proxy/haproxy/haproxy-2.0.0.ebuild#n101) for it
- it has to be turned on via config anyway, so its existence shouldn't impact performance

[contrib/prometheus-exporter/README](https://github.com/haproxy/haproxy/blob/19338011368b787b18598aac00bd639657f22bfa/contrib/prometheus-exporter/README):

> This service has been developed as a third-party component because it could
> become obsolete, depending on how much time Prometheus will remain heavily
> used. This is said with no ulterior motive of course. Prometheus is a great
> software and I hope all the well for it. But we involve in a environment moving
> quickly and a solution may be obvious today could be deprecated the next
> year. And because PROMEX is not integrated by default into the HAProxy codebase,
> it will need some interest to be actively supported. All contribution of any
> kind are welcome.
> 
> You must also be careful if you use with huge configurations. Unlike the stats
> applet, all metrics are not grouped by service (proxy, listener or server). With
> PROMEX, all lines for a given metric are provided as one single group. So
> instead of collecting all metrics for a proxy before moving to the next one, we
> must loop on all proxies for each metric. Same for the servers. Thus, it will
> spend much more ressources to produce the Prometheus metrics than the CSV export
> through the stats page. To give a comparison order, quick benchmarks shown that
> a PROMEX dump is 5x slower and 20x more verbose than a CSV export.
>
